/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["da8643013c2941f5ed7f8a9c9b4a7f7a"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive a Sanctum token */
        post: operations["535ffeda4b78916efd658b2844ea897a"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current access token */
        post: operations["46f8a14c8083abb69eed72768aa08629"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all stock holdings for the authenticated user */
        get: operations["f666637cf31343326959ad985974de34"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-holdings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single stock holding */
        get: operations["59fe3f2bd1e22b368a76026d37406bf4"];
        /** Update nickname or notes on a holding */
        put: operations["23f4b91e5a4241f9c588d249228af337"];
        post?: never;
        /** Soft-delete a stock holding and its parent holding record */
        delete: operations["eba40fe4a4d0e46ed10ce8214e8400d6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-holdings/{id}/computed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Computed metrics — quantity, avg buy price, cost basis, unrealized P&L */
        get: operations["dd961f5a0c2ab37fb098d4e9e0e4fba7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-holdings/{id}/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List FIFO lots for a holding — ordered oldest buy first */
        get: operations["7d90df3ee91e2db7cb85bec1f5732116"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-holdings/{id}/tax": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** STCG / LTCG tax breakdown computed from exhausted FIFO lots */
        get: operations["09dc49f8cc1f6dfe06d8e3f81fa37c18"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search NSE/BSE stock master by company name, symbol, or ISIN */
        get: operations["63ab5263a9bd8ee990a1bd73be243282"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single stock detail with meta and latest price */
        get: operations["fa1df0e540d2baee42cbd7250a65379d"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List corporate events (splits, bonuses, mergers) for a stock */
        get: operations["69f40360b544cae995fea00f2e8f5217"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-holdings/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all transactions for a holding, newest first */
        get: operations["6d35fee26ea6fe17e9d70336800daf1b"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a transaction — auto-creates the holding on first transaction for a stock + platform + exchange combination */
        post: operations["285aa1e6a2e46257dc9c4b8e3098aa91"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit a transaction — re-runs FIFO and recalculates holding on quantity change */
        put: operations["b441f42f6e0b3b99fbecce744a311cd3"];
        post?: never;
        /** Delete a transaction — restores FIFO lots if sell, soft-deletes lot if buy */
        delete: operations["015a64f77332ceef3e5c619ab17f4009"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List platforms that support a given asset type */
        get: operations["caf905e7ed08db934a97ce99cab2ca17"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    da8643013c2941f5ed7f8a9c9b4a7f7a: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Brijesh */
                    name: string;
                    /**
                     * Format: email
                     * @example brijesh@example.com
                     */
                    email: string;
                    /** @example secret123 */
                    password: string;
                    /** @example secret123 */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: {
                            id?: number;
                            name?: string;
                            email?: string;
                        };
                        token?: string;
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "535ffeda4b78916efd658b2844ea897a": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example brijesh@example.com
                     */
                    email: string;
                    /** @example secret123 */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: {
                            id?: number;
                            name?: string;
                            email?: string;
                        };
                        token?: string;
                    };
                };
            };
            /** @description Invalid credentials */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "46f8a14c8083abb69eed72768aa08629": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    f666637cf31343326959ad985974de34: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of stock holdings with parent holding, platform, and latest price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example 42 */
                            stock_id?: number;
                            /**
                             * @example NSE
                             * @enum {string}
                             */
                            exchange?: "NSE" | "BSE";
                            /**
                             * Format: float
                             * @example 10
                             */
                            quantity?: number;
                            /**
                             * Format: float
                             * @example 1500
                             */
                            avg_buy_price?: number;
                            holding?: {
                                id?: number;
                                nickname?: string | null;
                                notes?: string | null;
                                /** @example active */
                                status?: string;
                                /** @example 15000 */
                                principal_amount?: number;
                                platform?: Record<string, never>;
                            };
                            stock?: {
                                id?: number;
                                company_name?: string;
                                nse_symbol?: string;
                                latest_price?: Record<string, never> | null;
                            };
                        }[];
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "59fe3f2bd1e22b368a76026d37406bf4": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock holding detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "23f4b91e5a4241f9c588d249228af337": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example My INFY position */
                    nickname?: string | null;
                    /** @example Long term hold */
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description Holding updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eba40fe4a4d0e46ed10ce8214e8400d6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holding deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dd961f5a0c2ab37fb098d4e9e0e4fba7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computed metrics. current_price and unrealized_pnl are null when no daily price row exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 10 */
                            quantity?: number;
                            /** @example 1500 */
                            avg_buy_price?: number;
                            /** @example 15000 */
                            cost_basis?: number;
                            /** @example 1750 */
                            current_price?: number | null;
                            /**
                             * Format: date
                             * @example 2024-06-20
                             */
                            price_date?: string | null;
                            /** @example 17500 */
                            current_value?: number | null;
                            /** @example 2500 */
                            unrealized_pnl?: number | null;
                            /** @example 16.67 */
                            unrealized_pnl_pct?: number | null;
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "7d90df3ee91e2db7cb85bec1f5732116": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lot list with lock-in status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            id?: number;
                            /**
                             * Format: date
                             * @example 2024-01-10
                             */
                            buy_date?: string;
                            /** @example 1500 */
                            buy_price?: number;
                            /** @example 10 */
                            original_quantity?: number;
                            /** @example 6 */
                            quantity_remaining?: number;
                            /** @example false */
                            is_exhausted?: boolean;
                            /** @example false */
                            is_locked?: boolean;
                            /** Format: date */
                            locked_until?: string | null;
                        }[];
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "09dc49f8cc1f6dfe06d8e3f81fa37c18": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tax breakdown. LTCG exemption of ₹1 lakh applied at holding level. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 5000 */
                            stcg_gain?: number;
                            /** @example 750 */
                            stcg_tax?: number;
                            /** @example 120000 */
                            ltcg_gain?: number;
                            /** @example 100000 */
                            ltcg_exemption?: number;
                            /** @example 20000 */
                            ltcg_taxable_gain?: number;
                            /** @example 2000 */
                            ltcg_tax?: number;
                            /** @example 2750 */
                            total_tax?: number;
                            breakdown?: {
                                lot_id?: number;
                                /** Format: date */
                                buy_date?: string;
                                /** Format: date */
                                sell_date?: string;
                                holding_months?: number;
                                quantity?: number;
                                buy_price?: number;
                                sell_price?: number;
                                gain?: number;
                                /** @enum {string} */
                                type?: "STCG" | "LTCG";
                            }[];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "63ab5263a9bd8ee990a1bd73be243282": {
        parameters: {
            query: {
                /** @description Search term — company name, NSE/BSE symbol, or ISIN */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching stocks (max 20) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example INE009A01021 */
                            isin?: string;
                            /** @example Infosys Ltd */
                            company_name?: string;
                            /** @example INFY */
                            nse_symbol?: string;
                            /** @example INFY */
                            bse_symbol?: string;
                            /** @example 500209 */
                            bse_code?: string;
                            /** @example IT */
                            sector?: string;
                        }[];
                    };
                };
            };
            /** @description Validation error — q is required */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fa1df0e540d2baee42cbd7250a65379d: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stock ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stock not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "69f40360b544cae995fea00f2e8f5217": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stock ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Corporate events ordered by event_date desc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stock not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "6d35fee26ea6fe17e9d70336800daf1b": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            id?: number;
                            /** @enum {string} */
                            type?: "buy" | "sell" | "dividend" | "bonus" | "split";
                            /** @example 10 */
                            quantity?: number | null;
                            /** @example 1500 */
                            price_per_unit?: number | null;
                            /** @example 15000 */
                            amount?: number;
                            /**
                             * Format: date
                             * @example 2024-01-10
                             */
                            transaction_date?: string;
                            /** @enum {string} */
                            source?: "manual" | "csv_import" | "api_sync";
                            reference?: string | null;
                        }[];
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Holding not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "285aa1e6a2e46257dc9c4b8e3098aa91": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description ID from stocks master
                     * @example 42
                     */
                    stock_id: number;
                    /**
                     * @description Broker/platform ID
                     * @example 1
                     */
                    platform_id: number;
                    /**
                     * @example NSE
                     * @enum {string}
                     */
                    exchange: "NSE" | "BSE";
                    /**
                     * @example buy
                     * @enum {string}
                     */
                    type: "buy" | "sell" | "dividend" | "bonus" | "split";
                    /**
                     * @description Required for buy/sell
                     * @example 10
                     */
                    quantity?: number;
                    /**
                     * @description Required for buy/sell; amount auto-computed when both provided
                     * @example 1500
                     */
                    price_per_unit?: number;
                    /**
                     * Format: date
                     * @example 2024-01-10
                     */
                    transaction_date: string;
                    /**
                     * @example manual
                     * @enum {string}
                     */
                    source?: "manual" | "csv_import" | "api_sync";
                    /**
                     * @description Broker order ID
                     * @example ORD123456
                     */
                    reference?: string | null;
                    /**
                     * @description Only applied when a new holding is created
                     * @example My INFY position
                     */
                    nickname?: string | null;
                    /** @description Only applied when a new holding is created */
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description Transaction created; holding + lot auto-managed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error or locked lot */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    b441f42f6e0b3b99fbecce744a311cd3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 10 */
                    quantity?: number | null;
                    /** @example 1600 */
                    price_per_unit?: number | null;
                    /** Format: date */
                    transaction_date?: string | null;
                    reference?: string | null;
                };
            };
        };
        responses: {
            /** @description Transaction updated; FIFO and holding resynced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transaction belongs to another user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "015a64f77332ceef3e5c619ab17f4009": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction deleted; lots and holding resynced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transaction belongs to another user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    caf905e7ed08db934a97ce99cab2ca17: {
        parameters: {
            query?: {
                /** @description Filter by asset type, e.g. stock, mf, fd */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching platforms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
